#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cru_jc_base?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 001019
  thymeleaf:
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html

#服务器端口
server:
  port: 1019
  servlet:
    context-path: /cru_jc_base
  tomcat:
    uri-encoding: utf-8
  address: localhost